### ISSUE TITLE
The Hundred Page Machine Learning Book 

### ISSUE THREAD

**Issue by aburkov** [tirthajyoti/Papers-Literature-ML-DL-AI#2]
Hi,

I would appreciate if you replaced the chapters of my book by the links to the files on the book's website. The files on the book's website are constantly updated while those you put on github are stale and might leave wrong perception to the reader. 

Thank you,
Andriy Burkov

**Comment by sayakpaul** [comment]
Hi @aburkov. This has been resolved. You can it [here](https://github.com/tirthajyoti/Papers-Literature-ML-DL-RL-AI/tree/master/General-Machine-Learning/The%20Hundred-Page%20Machine%20Learning%20Book%20by%20Andriy%20Burkov). Let me know if this is fine.
